### ISSUE TITLE
Consider making voter eligibility per subgroup

### ISSUE THREAD

**Issue by brycelelbach** [brycelelbach/wg21_p2195_electronic_straw_polls#11]
A reviewer suggested this, and I think it's an interesting notion. Essentially instead of saying that you must have attended a previous face-to-face committee meeting in general, you'd need to have attended the specific subgroup in a previous face-to-face meeting.

I think it would resolve a lot of concerns that people may have, and adds a strength to asynchronous decision making that would be hard and potentially undesirable to enforce in synchronous meetings.

It would also help for study groups, who have constituencies that may not attend general purpose face-to-face meetings, but attend special sessions, like the SG14 CppCon meetings.

It does raise some potential concerns about gatekeeping. Additionally, it may create a lot of administrative overhead.

I hadn't seriously considered it before due to concerns of technical complexity, but I'm told that the isocpp.org login system already has a notion of "groups", so I think this would be fine.

**Comment by jfbastien** [comment]
I think this is better handled by having the chair judge consensus based on how knowledgeable the person voting is in a particular area. If I vote in SG1 then people usually pay attention, but if I vote in CWG/LWG/SG16 then my vote should be worth less, even if I have attended all of these recently. For bigger groups (such as LEWG or EWG), the comment left also helps the chair's understanding of a vote substantially because some participants can be knowledgeable without speaking up often (if at all), and some might attend frequently but not actually understand that particular subject (because EWG and LEWG tackle a wider variety of topics).

**Comment by inbal2l** [comment]
I agree with JF on this one. I think that limiting the votes to a smaller number of people is problematic, for two main reasons:
1. From what I've seen, even a non-expert on a specific field can have valuable input, and may even sway a vote. by limiting the voters, you also limit the input provided by the comment. I believe it's important to hear as much voices as possible before making decisions. (which is also an argument pro issue #12)
2. During meetings there are multiple sessions held at once, it is very possible that an expert on two different topics will not be able to attend, due to physical space limitations... :) Personally, I would love to collect their input on both of the topics.

**Comment by inbal2l** [comment]
I agree with JF on this one. I think that limiting the votes to a smaller number of people is problematic, for two main reasons:
1. From what I've seen, even a non-expert on a specific field can have valuable input, and may even sway a vote. by limiting the voters, you also limit the input provided by the comment. I believe it's important to hear as much voices as possible before making decisions. (which is also an argument pro issue #12)
2. During meetings there are multiple sessions held at once, it is very possible that an expert on two different papers' topics will not be able to attend, due to physical space limitations... :) Personally, I would love to collect their input on both of the papers. 
3. On top of all, I believe it will lead to a lot of technical difficulties, and 'special requests'. (if an author of a paper could not participate in the last meeting, will it make since to deny their vote? but that argument also goes to contributor, etc.)

**Comment by inbal2l** [comment]
I agree with JF on this one. I think that limiting the votes to a smaller number of people is problematic, for two main reasons:
1. From what I've seen, even a non-expert on a specific field can have valuable input, and may even sway a vote. by limiting the voters, you also limit the input provided by the comment. I believe it's important to hear as much voices as possible before making decisions. (which is also an argument pro issue #12)
2. During meetings there are multiple sessions held at once, it is very possible that an expert on two different papers' topics will not be able to attend, due to physical space limitations... :) Personally, I would love to collect their input on both of the papers. 

On top of that, I believe applying limitations will lead to a lot of technical difficulties, and 'special requests'. (if an author of a paper could not participate in the last meeting, will it make since to deny their vote? but that argument also goes to contributor, etc.)

**Comment by brycelelbach** [comment]
Alright. I'm going to close this. It's technically challenging, may limit our flexibility, and presents gatekeeping challenges.
