### ISSUE TITLE
Consider deleting detailed voter results after a short time period

### ISSUE THREAD

**Issue by ben-craig** [brycelelbach/wg21_p2195_electronic_straw_polls#4]
We may want to consider deleting the roll of voters two'ish weeks after the poll closes.  We should leave the roll of voters up for a short time so that people can verify the authenticity of the vote, but we shouldn't leave it up indefinitely.  Remove the roll of voters can reduce the temptation for someone to come along in a few years and dump the entire voting record on reddit.

**Comment by inbal2l** [comment]
Agreed. I believe it is important to align with the policy of confidential voting history (vs. confidential voting).

**Comment by jfbastien** [comment]
That temptation has been there for *years* with the meeting minutes, and never materialized. I agree that it's a valid concern, but again I'd rather trust that people are professional and will act in good faith, instead of penalizing everyone by setting up an adversarial system. If we design for adversaries, then we create adversaries.

There might be some middle ground here, but I really wouldn't approach this type of change with "what if we have a bad actor?" in mind.

**Comment by inbal2l** [comment]
If I understand correctly, the minutes have always been kept, but the votes (by name) never have (votes are much clearer deceleration than minutes). 
I'm not familiar with this topic's history, but I'm worried that our positive experience with our respective employees might effect our judgment. (I can't assume anything about others' experience). 

So in conclusion, I would suggest exposing names and comments during the vote (#12), publishing only numeric results. (which is the closest to what happens in a real meeting)

**Comment by brycelelbach** [comment]
I think we're not going to go this route, at least not at first. It's important to have records for accountability. Additionally, the other electronic balloting systems we interact with, such as ISOs and INCITSs, do preserve this history.
